server:
  port: ${PORT:8080}
spring:
  application:
    name: "herogame"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
  data:
    mongodb:
      uri: ${MONGO_URI:mongodb://localhost:27017}
      database: ${MONGO_DATABASE:herogame}
  rabbitmq:
    addresses: { BUS_URI:amqp://guest:guest@localhost:5672 }
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
queues:
  exchange: herogame
  game:
    name: game.handles
    routing:
      key: game.*

